spring:
  profiles:
    active: dev

  application:
    name: monew

#  server:
#    port: 8080

external:
  naver:
    api:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}


