spring:
  server:
    port: 8080

  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql

  datasource:
    url: jdbc:postgresql://ballast.proxy.rlwy.net:17988/railway
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${MONEW_DB_PASSWORD}

  data:
    mongodb:
      uri: mongodb://mongo:${MONGO_PASSWORD}@shortline.proxy.rlwy.net:44383

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_updates: true
    defer-datasource-initialization: true
    open-in-view: false

logging:
  level:
    root: info
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace