spring:
  server:
    port: 8080

  sql:
    init:
      mode: never
      schema-locations: classpath:sql/schema.sql

  datasource:
    url: jdbc:postgresql://ballast.proxy.rlwy.net:17988/railway
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${MONEW_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
        order_updates: true
    defer-datasource-initialization: true