-- ========================
-- Users (사용자)
-- ========================
CREATE TABLE users (
        id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        email       VARCHAR(255) NOT NULL UNIQUE,
        nickname    VARCHAR(100) NOT NULL UNIQUE,
        password    VARCHAR(255) NOT NULL,
        created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        deleted     BOOLEAN DEFAULT FALSE
);

-- ========================
-- Interests (관심사)
-- ========================
CREATE TABLE interests (
        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name                VARCHAR(255) NOT NULL UNIQUE,
        subscriber_count    BIGINT DEFAULT 0
);

-- ========================
-- keywords (키워드)
-- ========================
CREATE TABLE keywords (
        id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        keyword VARCHAR(255) NOT NULL UNIQUE
);

-- ========================
-- InterestKeywords (관심사-키워드, 다대다 매핑)
-- ========================
CREATE TABLE interest_keywords (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        interest_id     BIGINT NOT NULL,
        keyword_id      BIGINT NOT NULL,
        UNIQUE (interest_id, keyword_id),
        FOREIGN KEY (interest_id) REFERENCES interests(id) ON DELETE CASCADE,
        FOREIGN KEY (keyword_id) REFERENCES keywords(id) ON DELETE CASCADE
);

-- ========================
-- UserInterests (사용자-관심사)
-- ========================
CREATE TABLE user_interests (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id         UUID NOT NULL,
        interest_id     BIGINT NOT NULL,
        subscribed_by_me BOOLEAN DEFAULT FALSE,
        UNIQUE (user_id, interest_id),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY (interest_id) REFERENCES interests(id) ON DELETE CASCADE
);

-- ========================
-- Articles (뉴스 기사)
-- ========================
CREATE TABLE articles (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source          VARCHAR(255),
        source_url      TEXT,
        title           VARCHAR(500) NOT NULL,
        publish_date    TIMESTAMP,
        summary         TEXT,
        comment_count   INT DEFAULT 0,
        view_count      BIGINT DEFAULT 0,
        deleted         BOOLEAN DEFAULT FALSE
);

-- ========================
-- UserArticles (사용자-기사)
-- ========================
CREATE TABLE user_articles (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id         UUID NOT NULL,
        article_id      BIGINT NOT NULL,
        viewed_by_me    BOOLEAN DEFAULT FALSE,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
        UNIQUE (user_id, article_id)
);

-- ========================
-- Comments (댓글)
-- ========================
CREATE TABLE comments (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        article_id      BIGINT NOT NULL,
        user_id         UUID NOT NULL,
        content TEXT    NOT NULL,
        like_count      INT DEFAULT 0,
        liked_by_me     BOOLEAN DEFAULT FALSE,
        created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        deleted         BOOLEAN DEFAULT FALSE,
        FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE,
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ========================
-- User Comment Like (사용자-좋아요한 댓글)
-- ========================
CREATE TABLE user_comment_like (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id         UUID NOT NULL,
        comment_id      BIGINT NOT NULL,
        liked_by_me     BOOLEAN DEFAULT FALSE,
        UNIQUE (user_id, comment_id),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE
);

-- ========================
-- Notifications (알림)
-- ========================
CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    confirmed       BOOLEAN DEFAULT FALSE,
    user_id         UUID NOT NULL,        --FK
    content         TEXT,
    resource_type   VARCHAR(100),
    resource_id     UUID,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
